# Default values for coffee-svc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
domain: coffee-svc.minikube
image:
  repository: twelvelabs/coffee-svc
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: coffee-svc
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

