apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "shortname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - host: {{ .Values.ingress.subdomain | default .Release.Name }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "shortname" . }}
          servicePort: 80
